INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (1, 'MADEIRA', 315000);
INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (2, 'PEDRA', 1225000);
INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (3, 'MINERIO', 70000);
INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (4, 'MADEIRA', 37800);
INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (5, 'PEDRA', 308700);
INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (6, 'MINERIO', 50400);
INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (7, 'MADEIRA', 828000);
INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (8, 'PEDRA', 1610000);
INSERT INTO GERA_RECURSO(id_atuacao, recurso, qtd) VALUES (9, 'CHIP', 690000);
