INSERT INTO RECURSO_PRECISA_TECNOLOGIA (nome, nivel, recurso) VALUES ('MANUFATURA', 1, 'COMIDA');
INSERT INTO RECURSO_PRECISA_TECNOLOGIA (nome, nivel, recurso) VALUES ('MANUFATURA', 1, 'MADEIRA');
INSERT INTO RECURSO_PRECISA_TECNOLOGIA (nome, nivel, recurso) VALUES ('MANUFATURA', 1, 'PEDRA');
INSERT INTO RECURSO_PRECISA_TECNOLOGIA (nome, nivel, recurso) VALUES ('MANUFATURA', 1, 'MINERIO');
INSERT INTO RECURSO_PRECISA_TECNOLOGIA (nome, nivel, recurso) VALUES ('MANUFATURA', 1, 'CHIP');
INSERT INTO RECURSO_PRECISA_TECNOLOGIA (nome, nivel, recurso) VALUES ('TRANSPORTE', 1, 'NAVE');
INSERT INTO RECURSO_PRECISA_TECNOLOGIA (nome, nivel, recurso) VALUES ('ARMAMENTO', 1, 'ARMA');
INSERT INTO RECURSO_PRECISA_TECNOLOGIA (nome, nivel, recurso) VALUES ('MANUFATURA', 3, 'GERADOR');
