INSERT INTO RECURSOS (nome, volume) VALUES ('COMIDA', 0.5);
INSERT INTO RECURSOS (nome, volume) VALUES ('MADEIRA', 2);
INSERT INTO RECURSOS (nome, volume) VALUES ('PEDRA', 1);
INSERT INTO RECURSOS (nome, volume) VALUES ('MINERIO', 1);
INSERT INTO RECURSOS (nome, volume) VALUES ('CHIP', 0.1);
INSERT INTO RECURSOS (nome, volume) VALUES ('NAVE', 999999);
INSERT INTO RECURSOS (nome, volume) VALUES ('ARMA', 100);
INSERT INTO RECURSOS (nome, volume) VALUES ('GERADOR', 1000);
