-- Código para limpar todas as relações do BD
-- select 'drop table '||table_name||' cascade constraints;' from user_tables;
    drop table ATUACAO cascade constraints;
    drop table BATALHA cascade constraints;
    drop table CIVIL cascade constraints;
    drop table COLONIA cascade constraints;
    drop table CONHECIMENTO cascade constraints;
    drop table CONSTRUCAO cascade constraints;
    drop table ESPECIE cascade constraints;
    drop table ESTOQUE cascade constraints;
    drop table ESTOQUE_GASTO_BATALHA cascade constraints;
    drop table ESTRUTURA cascade constraints;
    drop table EXPLORACAO cascade constraints;
    drop table GERA_RECURSO cascade constraints;
    drop table IMPERIO cascade constraints;
    drop table INDUSTRIA cascade constraints;
    drop table MOVE_POVO cascade constraints;
    drop table MOVE_RECURSO cascade constraints;
    drop table PLANETA cascade constraints;
    drop table POVO cascade constraints;
    drop table POVO_MORTO_BATALHA cascade constraints;
    drop table PRIORIDADE_PRODUCAO cascade constraints;
    drop table RECURSOS cascade constraints;
    drop table RECURSO_PARA_ESTRUTURA cascade constraints;
    drop table RECURSO_PRECISA_TECNOLOGIA cascade constraints;
    drop table TECNOLOGIA cascade constraints;
